#!/bin/sh

head -n 31 ~/Dropbox/dev/font511/template.bdf > ~/.fonts/font511.bdf
tail -n +14 ~/Dropbox/dev/font511/font511.bdf >> ~/.fonts/font511.bdf

mkfontdir ~/.fonts
mkfontscale ~/.fonts
# xset +fp ~/.fonts

xset fp rehash
fc-cache
fc-cache -fv

fc-list | ag font511
