#!/bin/sh

head -n 31 template.bdf > ~/.fonts/font511.bdf
tail -n +14 raw.bdf >> ~/.fonts/font511.bdf

mkfontdir ~/.fonts
mkfontscale ~/.fonts
xset +fp ~/.fonts

xset fp rehash
fc-cache
fc-cache -fv

fc-list | grep font511
